apiVersion: v1
kind: Service
metadata:
  name: rsshub-service
  labels:
    app: RSSHub
spec:
  ports:
    - port: 80
      targetPort: 80
      NodePort: 30001
  selector:
    app: RSSHub
  type: NodePort
